### ISSUE TITLE
Validate free functions in Solidity 0.7.1

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#159]
Solidity 0.7.1 [introduces](https://solidity.ethereum.org/2020/09/02/solidity-0.7.1-release-announcement/) file-level free functions, which the plugins have to validate for upgrade safety. They behave just like internal library functions, and the implementation in the plugins should be the same too.

We have to get all referenced free functions, and then also run the appropriate validations in them.

https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/608f133bca3500e8721c0867ed9a534e7353aa20/packages/core/src/validate.ts#L74

I think the only relevant validations are "delegate call errors".

https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/608f133bca3500e8721c0867ed9a534e7353aa20/packages/core/src/validate.ts#L250-L253

We have to run these also in the free functions and then make a contract that references the function inherit its errors too.

~Note that `solidity-ast` doesn't support this new feature yet, so `findAll` will not find free functions in a file.~
`solidity-ast` supports free functions [since v0.4.4](https://github.com/OpenZeppelin/solidity-ast/releases/tag/v0.4.4).

**Comment by julianmrodri** [comment]
Hi, did some research on this.  It is **not that straightforward** but can certainly be accommodated in the current process with a few changes:

The main issues are:
1. These functions show up in `solc-output` as isolated `FunctionDefinition`, so with the current process they are not even picked up for validation (as we only analyze `ContractDefinition` which included Libraries). 
2. The function call look exactly like normal function calls, so they are not easily identified as Library calls (which use `type (library)` and can be uniquely identified.* 

To overcome this issues one possible **approach** is the following:

* In `validate.ts` create an additional step to get all `freeFunctions` and populate them in the `Validation` object.  The only field that would be completed though are the `errors` as it will not have any of the other attributes:

```javascript
  for (const fnDef of findAll('FunctionDefinition', solcOutput.sources[source].ast)) {
      fromId[fnDef.id] = fnDef.name;

      if (fnDef.kind === 'freeFunction') {
        validation[fnDef.name] = {
          inherit: [],
          libraries: [],
          freeFunctions: [],
          linkReferences: [],
          errors: [...getDelegateCallErrors(fnDef, decodeSrc)],
          layout: {
            storage: [],
            types: {},
          },
        };
      }
    }
```
* This requires to allow `getDelegateCallErrors` to run against `FunctionDefinition`, as shown here:

```javascript
function getDelegateCallErrors(
  contractDef: ContractDefinition | FunctionDefinition,
  decodeSrc: SrcDecoder,
): Generator<ValidationErrorOpcode> {
  for (const fnCall of findAll('FunctionCall', contractDef)) {
  ......  
  }
}
```
* For each `Contract` that gets processed, add the referenced `freeFunctions`. Because these calls look *exactly* like normal function calls, we can pass the `validation` object to confirm it is a freeFunction (it should have an entry in `validation`). We only need to cover `ExplicitUsage` (Implicit is not supported yet in Solidity).

```javascript
function getFreeFunctionIds(contractDef: ContractDefinition, validation: Validation): number[] {
  const explicitUsage = [...findAll('Identifier', contractDef)]
    .filter(identifier => identifier.typeDescriptions.typeString?.match(/^function/) && validation[identifier.name])
    .map(identifier => {
      if (isNullish(identifier.referencedDeclaration)) {
        throw new Error('Broken invariant: Identifier.referencedDeclaration should not be null');
      }
      return identifier.referencedDeclaration;
    });
  return [...new Set(explicitUsage)];
}
```

* Lastly when we get the `errors` we should concatenate as well the validations from `freeFunctions`. 

```javascript
export function getErrors(validation: Validation, version: Version): ValidationError[] {
  const contractName = getContractName(validation, version);
  const c = validation[contractName];
  return c.errors
    .concat(...c.inherit.map(name => validation[name].errors))
    .concat(...c.libraries.map(name => validation[name].errors))
    .concat(...c.freeFunctions.map(name => validation[name].errors));
}
```

This is one of the potential approaches, which has the main advantage of maintaining the current process that it is used with `Libraries`. It treats `FunctionDefinitions` for free functions similar to `Contracts` and allows them  to integrate them easily in the current flow.

**Comment by julianmrodri** [comment]
Another possible approach (which I haven't tried)  is to generate a new in-memory structure `freeFunctions` which will have all the free functions used and their errors.

```javascript
const freeFunctions[functionName] = {
        errors: [],
}
```
We can populate it like this:

```javascript
for (const fnDef of findAll('FunctionDefinition', solcOutput.sources[source].ast)) {
      if (fnDef.kind === 'freeFunction') {
        freeFunctions[fnDef.name] = {
          errors: [...getDelegateCallErrors(fnDef, decodeSrc)],
         };
      }
}
```

Then as part of the **error processing** for each `Contract` we can have a `getFreeFunctionErrors()` function that we can call to get all the errors of the references "free functions". 

```javascript

        validation[contractDef.name].errors = [
          ...getConstructorErrors(contractDef, decodeSrc),
          ...getDelegateCallErrors(contractDef, decodeSrc),
          ...getStateVariableErrors(contractDef, decodeSrc),
         ........
          ...getLinkingError s(contractDef, bytecode),

          // Free Function errors
          ...getFreeFunctionErrors(contractDef, freeFunctions),
        ];

```

in this new function `getFreeFunctionErrors` we can simply look for `functionCalls` to any of the `freeFunctions` that have at `errors.length > 0`. We do not care about free functions which are valid. In this approach we only include the errors without impacting of the other structures.

**Comment by frangio** [comment]
@julianmrodri Thank you so much for doing this work! :blush: I agree with most of what you said.

I think I would go with the in-memory approach, "flattening" free function errors into the contract when validations are constructed, rather than later in `getErrors`. I don't like the idea of overloading the `Validation` record to store functions as well, because there could be name clashes between functions and contracts.

There's something interesting that you didn't mention in your comment, which is that free functions may be using library functions. That means contracts can be using a library indirectly through a free function, which would need to be included in the list of libraries associated to the contract. The in-memory structure should have `errors` and `libraries` fields for each free function.

Note that we should identify functions strictly by their AST ids, because names are not guaranteed to be unique across a compilation.

@julianmrodri Do you want to go ahead and implement this?

**Comment by julianmrodri** [comment]
@frangio yes! I havent thought about that connection with Libraries, good catch.   

What should we do with for testing this feature? The current `truffle` and `buidler` projects are using `v0.5`, and for `core` we use `v0.6`.  Now we need to create a contract and test cases for `v0.7`. Let me know what is the best approach and i can implement.

**Comment by frangio** [comment]
I would be fine with upgrading truffle and buidler tests to solc 0.7.
