### ISSUE TITLE
Register impls in network file when source is available

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#175]
Some users may want to register an existing proxy for use with the plugins. It's possible to do this if the source code for the implementation is available. We should try to do this automatically on `deployProxy` and `upgradeProxy`, and maybe provide a way for the user to trigger it manually.

Related to https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/174.

**Comment by frangio** [comment]
I took a shot at this but it's a bit more work than I expected. The reason is that our "version" concept (which is used by the `impl-store` module, where we would add a new `registerImplDeployment` function) hashes the contract creation code, and in order to verify that a local contract is the same as an on chain contract we have to compare the "other" bytecode, that is contained in the artifacts but not in the ContractFactory abstraction.

**Comment by bonedaddy** [comment]
> I took a shot at this but it's a bit more work than I expected. The reason is that our "version" concept (which is used by the `impl-store` module, where we would add a new `registerImplDeployment` function) hashes the contract creation code, and in order to verify that a local contract is the same as an on chain contract we have to compare the "other" bytecode, that is contained in the artifacts but not in the ContractFactory abstraction.

Do you still have the code from when you took a shot at it that you can share?

**Comment by frangio** [comment]
Sorry, I discarded it because I think the implementation will have to be pretty different to the approach I took.

**Comment by marceljay** [comment]
As we encountered the issue in our hardhat setup with the OZ plugin, I posted in the OZ forum:
https://forum.openzeppelin.com/t/hardhat-uups-deployment-at-address-0x-is-not-registered/16529

**Comment by jimrubenstein** [comment]
I definitely need this feature; migration failures happen way too often using truffle, and the last time it happened I manually called the ProxyAdmin to update the implementation address.

Now, I need to run another upgrade, but can't, because the migration didn't complete the last time - so openzep didn't store the deployed contract address. So now, we get an error during upgrade and the only way I can think to get around it is to roll back the implementation to the previous version, and then run the migration again - as if the version in between never existed.

**Comment by ericglau** [comment]
The latest release of the plugins now have a `forceImport` function that can import a previously deployed proxy.
Refer to the documentation for the `forceImport` function for [Hardhat](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#force-import) or [Truffle](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-truffle-upgrades#force-import).

**Comment by lhernaro** [comment]
@ericglau Reading the documentation, it is not clear to me how to call the function you mention from the executor js file, could you add an example with truffle to the documentation?

**Comment by ericglau** [comment]
@lhernaro Can you elaborate on your scenario?  What do you mean by executor js file, and are you using it in test cases or migrations?  

You can also take a look at the [testcases for more examples](https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/052a09900804fdb66be4deec7f19f1930b45487e/packages/plugin-truffle/test/test/import.js#L54).  Please let me know which aspect of the documentation is not clear and we can consider improving it.  Thanks.

**Comment by lhernaro** [comment]
@ericglau I am testing it in the development environment, since due to network problems I assume I did not finish implementing the upgrade of my proxy, and in the manifest56 .json file where I understand the implementations are saved, the last one was not saved, so which I can not upgrade again,

I want to understand how to call the force import function since it is not clear to me, using trufle I imagine that it must be the same as calling the upgrade function, my upgrade function is like this

```const { upgradeProxy } = require('@openzeppelin/truffle-upgrades');

const ProxyOld = artifacts.require('LogicV3');
const ProvyNew= artifacts.require('LogicV4');

module.exports = async function (deployer) {
  const existing = await ProxyOld .deployed();
  const instance = await upgradeProxy(existing.address, ProvyNew, { deployer });
  console.log("Upgraded", instance.address);
}`

I understand that the force function should implement it in a similar way to this one, right?

**Comment by ericglau** [comment]
@lhernaro If you are sure that your proxy was already upgraded to LogicV4To, then you should be able to import it like this:
```
const ProxyOld = artifacts.require('LogicV3');
const ProvyNew= artifacts.require('LogicV4');

module.exports = async function (deployer) {
  const existing = await ProxyOld .deployed();
  const instance = await forceImport(existing.address, ProvyNew, { deployer });
  console.log("Imported", instance.address);
}
```
or if you know the proxy address, you can import it directly without using `.deployed()`, for example:
```
const ProvyNew= artifacts.require('LogicV4');

module.exports = async function (deployer) {
  const instance = await forceImport(MY_EXISTING_PROXY_ADDRESS, ProvyNew, { deployer });
  console.log("Imported", instance.address);
}
```

**Comment by lhernaro** [comment]
@ericglau Thank you very much, it has worked perfectly for me, I had been trying to solve it for days, since due to instabilities in the network where my proxies are executed, especially in test networks, it happens to me that truffle often deploys in the blockchain but does not finish confirm the blocks and in the json file where it saves the pointers it does not overwrite, and it always gave me this error, with this solution the truth is that it helps a lot, again ,thank you very much
