### ISSUE TITLE
Do you plan to port ProxyFactory contract?

### ISSUE THREAD

**Issue by marcelomorgado** [OpenZeppelin/openzeppelin-upgrades#215]
Hi, I'm using `@openzeppelin/upgrades` dependency (from `openzeppelin-sdk` repo) because of the upgradability contracts. I see that the `core` package has some of the previous contracts but the `ProxyFactory` is missing. It's blocking me to upgrade my contracts because I'm using this contract ([that deploy function](https://github.com/OpenZeppelin/openzeppelin-sdk/blob/master/packages/lib/contracts/upgradeability/ProxyFactory.sol#L37) in special).

Thanks!

**Comment by frangio** [comment]
Hi @marcelomorgado. The proxy contracts were moved from OpenZeppelin SDK to [OpenZeppelin Contracts](https://github.com/OpenZeppelin/openzeppelin-contracts). The upgrades plugins still haven't been updated to use those (see #164).

We have an issue for a proxy factory at https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2339. However, it's not a priotity right now because it's possible to write a proxy factory by hand in simple and secure code.

The only thing that may be harder is getting deterministic addresses via `create2` to work, although that should also be possible using our [`Create2`](https://docs.openzeppelin.com/contracts/3.x/api/utils#Create2) wrapper. There is [a guide](https://forum.openzeppelin.com/t/guide-to-using-create2-sol-library-in-openzeppelin-contracts-2-5-to-deploy-a-vault-contract/2268) to using this library in the forum.

Let us know over at https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2339 if you think there is more value that could be provided by a proxy factory contract.
