### ISSUE TITLE
Only consider errors from the library functions in use

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#240]
Our current checks will look at an entire library and consider it either upgrade safe or not. Due to this lack of granularity, a new function we wanted to introduce in the `Address` utility library in OpenZeppelin Contracts 3.3 caused the entire library to be unusable with the upgrades plugins. (https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/230)

We should only consider errors from those functions that are in use.

This opens an entire can of worms because we obviously need to consider errors from functions used indirectly (by the functions that are used directly, and so on transitively). The logic to implement this probably shares a lot with #159 so I would consider fixing both of these issues at the same time.

**Comment by kevupton** [comment]
Agree, it is a bit annoying to have a mix of upgrade safe and non-upgrade safe contracts in a project. is there any way for it to just search the contract being deployed? Instead of the entire library?

**Comment by frangio** [comment]
@kevupton Sorry this is not trivial to fix which is why we haven't done it yet.

**Comment by Na3aga** [comment]
Hi, guys. Is this still an issue? 

I have my upgradeable contract operating with **ERC20** contracts using the **SafeMath** library which includes the **Address** utility library. And it also causes my Contract to be considered as not safely deployed by your **hardhat-upgrades** tool. This is very weird because I don't try to make third-party **ERC20** contracts _upgradeable_.
Should I use **SafeMathUpgradeable** for interactions with non-upgradeable contracts ?????

**Comment by frangio** [comment]
I'm not sure I understood the full picture but I think the answer to your question is yes. Can you share an example code snippet?

**Comment by Mouzayan** [comment]
@frangio I am encountering the same error.
I have UUPS upgradeable contracts imported as dev dependencies, as well as one Transparent proxy upgradeable contract also imported as a dependency.
When I deploy them in my tests for my contract to interact with them, I get an error saying that the UUPS upgradeable contracts are 
```
not upgrade safe.
@openzeppelin/contracts/utils/Address.sol:191: Use of delegatecall is not allowed.
```
The upgradeable contracts are using AddressUpgradeable... so not sure why this issue is occurring.

**Comment by Na3aga** [comment]
> I'm not sure I understood the full picture but I think the answer to your question is yes. Can you share an example code snippet?

I have solved it by ignoring the error and silencing the warning. 
The issue is, that my Upgradeable contract calls non-upgradeable ERC20 Contracts, and I have the line:
`  using SafeERC20 for IERC20;`
And because your upgrade-validation tool is not "smart" in the dependencies checking, it throws an error on any use of the library that has Upgradeable analog, even if it is not used as upgradeable

**Comment by Mouzayan** [comment]
> > I'm not sure I understood the full picture but I think the answer to your question is yes. Can you share an example code snippet?
> 
> I have solved it by ignoring the error and silencing the warning. The issue is, that my Upgradeable contract calls non-upgradeable ERC20 Contracts, and I have the line: ` using SafeERC20 for IERC20;` And because your upgrade-validation tool is not "smart" in the dependencies checking, it throws an error on any use of the library that has Upgradeable analog, even if it is not used as upgradeable

I can silence the error in my test, but these upgradeable contracts I am interacting are on Mainnet.
So when i deploy my contract, it won't be possible to` unsafeAllow`.
I'm assuming this will be an issue...

**Comment by frangio** [comment]
Please post on [OpenZeppelin Forum](https://forum.openzeppelin.com/) with the affected Solidity code.

**Comment by Mouzayan** [comment]
> Please post on [OpenZeppelin Forum](https://forum.openzeppelin.com/) with the affected Solidity code.

@frangio Please see here:
https://forum.openzeppelin.com/t/interacting-with-uups-upgradeable-contracts-throwing-contract-is-not-upgrade-safe-use-of-delegatecall-is-not-allowed/32743

**Comment by matilareo** [comment]
Hi ! iam having the same issue when deploy a very basic contract. Is there any workaround ?
