### ISSUE TITLE
receive will result with out-of-gas

### ISSUE THREAD

**Issue by pinglamb** [OpenZeppelin/openzeppelin-upgrades#258]
Currently, the `receive()` of proxy is calling `_fallback()` (https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/core/contracts/proxy/Proxy.sol#L25). When this method is invoked by `send` and `transfer`, the transaction will fail with `out-of-gas` as only 2300 gas is available.

**Comment by frangio** [comment]
Hi @pinglamb. Can you provide more details about this? What contract did yout test this with, and how much gas did you find was necessary?

**Comment by pinglamb** [comment]
I have crafted a demo for showcasing the issue: https://github.com/pinglamb/send-to-proxy/tree/master/contracts

The `Receiver` contract is deployed behind `Proxy`. Whenever another contract (e.g. `Sender`) needs to send ether using the `transfer` method (https://docs.soliditylang.org/en/v0.6.0/contracts.html#receive-ether-function), `out-of-gas` will be resulted because the `Proxy` `receive()` function is called instead. 

You can check the test case of the demo project, which will result with:

```
Error: Returned error: VM Exception while processing transaction: revert
```

It works when the non-Proxy version is deployed instead.

A use case that will hit this issue is when the contract is interacting with `WETH` `withdraw` method (https://github.com/makerdao/sai/blob/master/src/weth9.sol#L41), which calls `transfer` to send ether.

**Comment by frangio** [comment]
This is a known issue. Please see [OpenZeppelin upgradeable contracts affected by Istanbul hardfork](https://forum.openzeppelin.com/t/openzeppelin-upgradeable-contracts-affected-by-istanbul-hardfork/1616). 

We haven't fixed it due to the small percentage of affected contracts. Your use case of the WETH withdraw method is a very interesting data point, though. An alternative implementation of proxies like UUPS (https://github.com/OpenZeppelin/openzeppelin-contracts/issues/2421) could help, though it might still be too tight on gas. Please show your support on that issue so we take it into consideration for prioritization!

**Comment by cryptostaker2021** [comment]
Hey @frangio 

We are facing same issue with Transparent Upgradable proxy deployed using hardhat plugin. What's your recommendation on this?

**Comment by frangio** [comment]
@cryptostaker2021 This is a known limitation of transparent proxies. [EIP-2930 access lists](https://eips.ethereum.org/EIPS/eip-2930) may offer a workaround.
