### ISSUE TITLE
Manifest file is always named `unknown-1337.json` even if network id is different

### ISSUE THREAD

**Issue by JasoonS** [OpenZeppelin/openzeppelin-upgrades#304]
When using the `@openzeppelin/truffle-upgrades` plugin, it always calls the manifest file `unkown-1337.json` if the network isn't known, even if the network id is different to 1337.

To test this you can run ganache with different network ids. eg. `ganache-cli --networkId 321`

This behaviour also happens for other networks (not just ganache), eg binance smart chain testnet has network id 97, but it still calls the manifest file `unkown-1337.json`.

**Comment by frangio** [comment]
Hi @JasoonS, this is because the number we use is not the network id but the chain id. There seems to be a `--chainId` option in Ganache according to https://github.com/trufflesuite/ganache-core/issues/515#issuecomment-700301787. Can you try that and let me know if it achieves the effect you want?

As for binance testnet, is this a local network like Ganache or a remote network you're connecting to?

**Comment by frangio** [comment]
Feel free to reopen is this is not solved.
