### ISSUE TITLE
Support beacon proxies

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/openzeppelin-upgrades#342]
Given that OpenZeppelin Contracts contains beacon proxies, it would be expected that the Upgrades Plugins should support them as well.

It is not clear if this should take the form of a `kind: 'beacon'` option to `deployProxy`, or if it should be a new family of functions: `deployBeacon` and `upgradeBeacon`. It seems that people interested in beacons will exclusively be those using on chain factories of upgradeable contracts, so `deployProxy` might not really be the right abstraction for them, although it would certainly be useful for testing, so we might want both.

**Comment by bundle-boy** [comment]
Nearing two months since this has been published. Any updates here?

Also wondering why beacon proxies aren't supported in the upgrades plugin; it does seem like a fairly niche use-case, but would be a nice quality of life improvement to be able to use the plugin on these.

**Comment by frangio** [comment]
@bundle-boy We agree it would be awesome to support beacon proxies here and hope we can work on this in the next few weeks.

Can you comment on the question of `deployBeacon` vs `deployProxy`? I'd love to hear how you would expect to use the plugin in the context of beacon proxies so we can have more clarity on the direction we should take.

**Comment by ylv-io** [comment]
I want to share my experience using beacon proxies for development and deployment. We use on-chain factory to deploy beacon proxies so we don't need `deployBeacon` functionality at all. Even tests use factory class to test for upgradability. We do use method `upgradeBeacon` to upgrade our beacon proxies via Hardhat script which is quite handy. Unfortunately, right now script is not capable to verify storage and other checks due to using `hardhat-deploy` for deployment so we are doing line by line peer review in case of upgrade.
I would say having an ability to run checks before calling an upgrade method is the biggest value proposition. Writing a script to deploy or upgrade a beacon proxy is trivial. Checking for upgradability compatibility is not. Especially in case of using different deployment solutions. Just using `artifacts` folder as a place to store deployed artifacts is not viable for most projects.

**Comment by frangio** [comment]
A note for people subscribed: we have one last simplification pending before we release this but it should not be long.

**Comment by leonwilly** [comment]
Any update on when this will be officially supported? I see #491 is pending review, is this the last simplification before beacon upgrades are put in production?

**Comment by frangio** [comment]
@leonwilly Yes, will be done this week.
