### ISSUE TITLE
plugin-hardhat upgradeProxy upgradeTo call doesnt await receipt 

### ISSUE THREAD

**Issue by jacobrosenthal** [OpenZeppelin/openzeppelin-upgrades#354]
Weve largely had success with manual one off upgrades until when we started to script multiple upgrades at a time and kept getting 
```
ProviderError: Transaction gas price supplied is too low. There is another transaction with same nonce in the queue. Try increasing the gas price or incrementing the nonce.
```

Adding an `await receipt.wait();` after `upgradeTo` seemed to fix it for us
https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/master/packages/plugin-hardhat/src/upgrade-proxy.ts#L37

But it seems like the codebase should be combed for other receipts it might be eating?

**Comment by frangio** [comment]
Thanks for reporting this issue!

We've purposely avoided unnecessarily waiting for transactions to mine, since it can introduce unwanted delays. In your case it seems like you want that delay, but the plugin doesn't give you any way to do that.

Something we could do is to set the upgrade transaction as the `deployTransaction` of the contract we return.

https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/0c2429c67ffd2a52d091e384fa4d6e3d058faf7a/packages/plugin-hardhat/src/deploy-proxy.ts#L84

If we did this you would be able to write

```javascript
const v2 = await upgrades.upgradeProxy(proxyAddress, ImplV2);
await v2.deployed();
```

Would this work for you?

As a workaround, I think you should be able to use [`NonceManager`](https://docs.ethers.io/v5/api/experimental/#experimental-noncemanager) to avoid resending a transaction with the same nonce, without the need to await in the middle.

**Comment by frangio** [comment]
Fixed in https://github.com/OpenZeppelin/openzeppelin-upgrades/commit/1c92fb7d7551d28e8af8aadd8d7c6f2d0376fd0e#diff-b28b1ed9821f38c64524ea13e19264bb0772f8376afffd5d8a1f8277621833eb and released in the latest version of the Hardhat plugin.

@jacobrosenthal Please try it out and let me know. Both `.deployed()` and `.deployTransaction.wait()` should work.

**Comment by 5hanth** [comment]
@frangio curious if this can help my use-case. I want to deploy the new implementation and store that TX that will be used for a Governance voting eventually by `_authorizeUpgrade(address newImplementation)` to check if the given implementation has enough votes to go through. so far it appears to me that there isn't a way to make the deployment of v2 first and call upgrateTo at a later stage.  Please correct me if I'm missing anything here.

**Comment by Amxx** [comment]
Hello @5hanth 

You can use the `prepareUpgrade` function. This will check the compatibility of the new implementation and deploy it to chain but NOT make the upgrade.

This function will return the instance of the newly deployed version.

You can then do you governance operation and perform the upgrade at a later stage.

**Comment by 5hanth** [comment]
@Amxx Yes, I was planning in that approach. But for some reason calling `MyContractV1.upgradeTo(implAddress)` fails with reason `Address: low-level delegate call failed`. Is this not the native way of upgrading after `prepareUpgrade` via plugin?

**Comment by frangio** [comment]
If you're using transparent proxies (the default) you need to call the `upgrade` function of the `ProxyAdmin` contract. You can find the `admin` address in your `.openzeppelin/mainnet.json` file (or other network).

**Comment by 5hanth** [comment]
@frangio I'm using UUPS

**Comment by frangio** [comment]
@5hanth Can you post your question on the [OpenZeppeiln Forum](https://forum.openzeppelin.com/)? Include more details about how you have defined `_authorizeUpgrade`.

**Comment by 5hanth** [comment]
I'll post on OpenZeppelin. Just in case anyone wants to know this:  

```
function _authorizeUpgrade(address newImplementation)
        internal
        override
        view
    {
        require(
            hasRole(DEFAULT_ADMIN_ROLE, msg.sender));
        require(approvedProposalsExpiry[newImplementation] > block.timestamp);
    }

```

signer has an admin role. The error occurs on reading any state variable.

**Comment by joaquinperea** [comment]
Hi guys! I'm deploying a proxy contract and its implementation using "deployProxy" instruction but I get a "Timed out waiting for transaction" error. I use ".deployed()" to await transaction mined but is not working. Am I doing something wrong?

**Comment by frangio** [comment]
@joaquinperea You're not doing anything wrong. If it times out, you can retry the same `deployProxy` function call and it will resume waiting for the same transaction.

**Comment by zhibo-noumena** [comment]
Hello,

It seems now deployed() is deprecated, I am using await .waitForDeployment(), and it still returns before the contract getting upgraded.
