### ISSUE TITLE
error : The requested contract was not found. Make sure the source code is available for compilation

### ISSUE THREAD

**Issue by Tom1054** [OpenZeppelin/openzeppelin-upgrades#379]
Firstly , I have already deployed *.sol in bsc testnet ,but I redeployed a second time ，and it appeared this error:

The requested contract was not found. Make sure the source code is available for compilation. I didn't change the code in the process

**Comment by Amxx** [comment]
Hello @Tom1054 

One does not deploy a solidity file. What you deploy is a contract's bytecode, which is the result of compiling it. It is likely you used some tooling for that (truffle ? hardhat ? remix ?)

Without more details about the tooling, there is nothing we can do to help you. Also, it's likely that this issue is a result of the tooling and not of our contracts. I encourage you to ask the question there, once you find out more details about what is happening. Ideally, you will want a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
