### ISSUE TITLE
docs/ folder navigation does not work well

### ISSUE THREAD

**Issue by RusAlex** [OpenZeppelin/openzeppelin-upgrades#380]
When open docs/modules/ROOT folder in project root, there is nav.adoc file. I suppose the file is for antora, although I did not use this software. But when you click on any navigation link in nav.adoc, 404 error comes. Maybe it's Github adoc parser issue, or maybe we can setup antora the way both navigation will work and antora results and github folder navigation with adoc parser. 

If somebody can point me out how to fix it, I would able to do a PR.

**Comment by Amxx** [comment]
Hello @RusAlex 

404 are because the link are not relative but absolute. Example of link:

```  <a class="link nav-link" href="/contracts/4.x/erc20.html">```

For the links to work, you need to serve these pages through a web server that places its root at `build/site`

If you want to modify the documentation, and check the results locally, you should probably use the `npm run docs:watch` command, which will start a webserver at `http://localhost:8080` with the right settings

**Comment by RusAlex** [comment]
ok. I thought it's supposed to work via github documentation render. Which would be useful.
