### ISSUE TITLE
artifacts.new vs ethers.getContractFactory.deploy()

### ISSUE THREAD

**Issue by noobshow** [OpenZeppelin/openzeppelin-upgrades#410]
Which one would be preferable?
using :

```
// test/Box.test.js

// Load dependencies
const { accounts, contract } = require('@openzeppelin/test-environment');
const { expect } = require('chai');

// Load compiled artifacts
const Box = contract.fromArtifact('Box');

// Start test block
describe('Box', function () {
  const [ owner ] = accounts;

  beforeEach(async function () {
    // Deploy a new Box contract for each test
    this.contract = await Box.new({ from: owner });
  });

  // Test case
  it('retrieve returns a value previously stored', async function () {
    // Store a value - recall that only the owner account can do this!
    await this.contract.store(42, { from: owner });

    // Test if the returned value is the same one
    // Note that we need to use strings to compare the 256 bit integers
    expect((await this.contract.retrieve()).toString()).to.equal('42');
  });
});
```

or 

```
// scripts/create-box.js
const { ethers, upgrades } = require("hardhat");

async function main() {
  const Box = await ethers.getContractFactory("Box");
  const box = await upgrades.deployProxy(Box, [42]);
  await box.deployed();
  console.log("Box deployed to:", box.address);
}

main();
```

What reasons to use one vs the other?
I have no use for specifics of `@openzeppelin/test-environment`, is there any benefits over one?

**Comment by frangio** [comment]
Your first example creates a regular contract, and your second example creates an upgradeable contract. To learn about upgradeability read [Upgrading smart contracts](https://docs.openzeppelin.com/learn/upgrading-smart-contracts).

If you have any further questions please ask over at https://forum.openzeppelin.com

**Comment by noobshow** [comment]
So, the `openzeppelin/test-environment` works as a test helper, it doesn't determine upgradability?

I was hoping it uses a different process than the usual hardhat `deploy` since it uses a different syntax `Contract.new`

**Comment by julianmrodri** [comment]
> So, the `openzeppelin/test-environment` works as a test helper, it doesn't determine upgradability?
 
Right. 

> I was hoping it uses a different process than the usual hardhat `deploy` since it uses a different syntax `Contract.new`

The problem is your two examples do different things, not very comparable. If what you want is to deploy an Upgradeable contract follow the links that fran provided and you will most likely be doing something similar to your 2nd example (taking advantage of the `upgrades-plugin` for Hardhat).

If you just were curious about the syntax difference, the first one uses the `oz/test-environment` libraries/tools/classes (which under the hood uses `web3.js`) and the second one is more Hardhat + `Ethers.js`. Just different ways of deploying contracts but the end result will be the same on the blockchain. (Again.. not for your example but assuming you posted similar/comparable things).

**Comment by noobshow** [comment]
Thanks for all details, glad to know about it...

I was reading about the artifacts in a post talking about upgradablility and automating tests around it...

Just in a snap I figured that differences, hence my question here...
Will be reminded to use the forum the next time.

Thanks once again
