### ISSUE TITLE
Meta: Add support for currently unsupported types.

### ISSUE THREAD

**Issue by Amxx** [OpenZeppelin/openzeppelin-upgrades#527]
- [x] #526
  - Function types, introduced in solidity 0.4.16 ?
  - Does not cause a parsing error, but storage checks fails
- [ ] #477
  - User defined value types, introduced in solidity 0.8.8
  - Parsing fails

**Comment by leonwilly** [comment]
Would it be possible to add a `ignore` flag for future solidity changes that may end up making upgrades unusable like the above. If one could `/// @custom:oz-upgrades-unsafe-allow ignore` or similar the checking could just skip the incompatibility and continue checking the rest of the storage layout. Otherwise when an incompatibility presents itself we are forced to use the unchecked and dangerous `upgradeTo` method.

**Comment by frangio** [comment]
>Would it be possible to add a ignore flag for future solidity changes that may end up making upgrades unusable like the above

There is now a flag `unsafeSkipStorageCheck` that may help in some cases, but for example will not help with the lack of support for user defined value types.

In some cases it will simply not be possible to "ignore" the issue. "Ignore" would just be using Ethers.js directly.

**Comment by frangio** [comment]
Closing this meta issue as function types have been fixed and the only other one is user defined value types.
