### ISSUE TITLE
Retrieving proxy address from network .openzeppelin files

### ISSUE THREAD

**Issue by FredCoen** [OpenZeppelin/openzeppelin-upgrades#616]
prepareUpgrades() requires the proxy address as an input. It would be helpful if this could be retrieved from the network files. Is there a way to do this or is one supposed to manually input a string, and change that string whenever the upgrade concerns a different network? Thanks

**Comment by ericglau** [comment]
There currently isn't a way to retrieve deployed proxy contracts - see https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/449

You would need to manually input a string, or (if you have a contract instance in your code for the previously deployed proxy) you can pass in the contract instance instead of an address string.

**Comment by FredCoen** [comment]
I see thanks for pointing to the discussion. Thats a shame cause i feel it quite prone to human errors
