### ISSUE TITLE
how to deployProxy with mutlisig or defender

### ISSUE THREAD

**Issue by FredCoen** [OpenZeppelin/openzeppelin-upgrades#617]
prepareUpgrade allows to add the option of getting the transactionResponse instead of actually upgrading so that the input data can be used to submit via a multisig. How can the same be achieved for deployProxy?

**Comment by ericglau** [comment]
There are a number of topics covered by your question, so I will address them separately below:

---

About `prepareUpgrade`:

`prepareUpgrade` does not actually perform an upgrade, regardless of its options.  It only validates that a new implementation is upgrade safe (compared to the old implementation), and deploys the new implementation.  It does not upgrade the proxy itself.

With `prepareUpgrade`, its [`getTxResponse` option](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#prepare-upgrade) allows it to return a transaction response (rather than the address) of the deployment of the new implementation.  It still actually deploys the new implementation; this option only affects what is returned.

---

About multisigs and Defender:

You can use the [`defender.proposeUpgrade` function](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#defender-propose-upgrade), which does the same thing as `prepareUpgrade` but also creates a Defender proposal to upgrade the proxy.  This proposal can be used with a multisig.

See [this tutorial](https://docs.openzeppelin.com/defender/guide-upgrades) for reference.

---

About `deployProxy`:

When you refer to getting the upgrade transaction instead of actually upgrading, that is covered by https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/185 .  In that case, "How can the same be achieved for deployProxy" does not make sense because `deployProxy` only deploys the initial implementation and proxy.  

Can you be more specific about what is your expected use case with `deployProxy`?

**Comment by FredCoen** [comment]
@ericglau thanks for the detailed response ! In the case of prepareUpgrade the signer linked to hardhat will deploy the logic contract (this can only be an EOA). The return value is a TransactionResponse which contains the data field that can be copied and used to send the transaction via the multisig. Is that right?

using defender proposeUpgrade has the advantage of not having to manually copy pasting that data input field and manually preparing the transaction via a multisig correct?

We are using the UUPS proxy pattern. If deployProxy deploys the implementation directly that means that the owner can only be an EOA. Is it not possible to have deployProxy return a transactionResponse for the implementation deployment so that the multisig can deploy it and be set as the owner directly. Or can we only deploy with EOA and then transfer ownership?

**Comment by ericglau** [comment]
> In the case of prepareUpgrade the signer linked to hardhat will deploy the logic contract (this can only be an EOA). The return value is a TransactionResponse which contains the data field that can be copied and used to send the transaction via the multisig. Is that right?

I don't think a multisig is needed for this step.  The logic (implementation) contract can be deployed by an EOA, and this is fine because the proxy can just point to this implementation (but using the proxy's state).  It does not matter who deployed the logic contract, since the logic contract itself is immutable and you can verify its source code.

> using defender proposeUpgrade has the advantage of not having to manually copy pasting that data input field and manually preparing the transaction via a multisig correct?

Yes, but let me re-emphasize, prepareUpgrade does not even create an upgrade transaction (but defender.proposeUpgrade does).

> We are using the UUPS proxy pattern. If deployProxy deploys the proxy and the implementation with an EOA and call the initialiser that means that the owner (who can upgrade) will be set to the EOA. Does the owner status have to manually transferred to a mutisig? Or is there any other option?

You could transfer the owner to the multisig in the initializer.

**Comment by FredCoen** [comment]
Thanks for your responses @ericglau its all clear now. Jus tone question on prepareUpgrade, (cause we havent set up defender yet to use proposeUpgrade), it will only deploy new implementation. it will not generate the transaction input field for the upgrade. That transaction has to be done manually by oneself ?

**Comment by ericglau** [comment]
> Jus tone question on prepareUpgrade, (cause we havent set up defender yet to use proposeUpgrade), it will only deploy new implementation. it will not generate the transaction input field for the upgrade. That transaction has to be done manually by oneself ?  

After you do prepareUpgrade, you can use Defender Admin to create an [upgrade action](https://docs.openzeppelin.com/defender/admin#upgrades).

**Comment by FredCoen** [comment]
thanks all very clear
