### ISSUE TITLE
useDeployedImplementation not working 

### ISSUE THREAD

**Issue by DmytroShalaiev** [OpenZeppelin/openzeppelin-upgrades#629]
I write such code, but when running script NEW proxy deployed but OLD implementation used

`  const proxy = await upgrades.deployProxy(MyContract, [], {
    useDeployedImplementation: false,
  });`
  
  Maybe I miss something

**Comment by ericglau** [comment]
The `useDeployedImplementation` option is only for preventing the function from deploying a new implementation when it is set to `true`.  But regardless of that option, if the same implementation was previously deployed on the network, any new proxy deployments would still point to that previously deployed implementation (because there is no need to deploy a new copy of the implementation, because its bytecode is identical).  See further discussion on [this forum thread](https://forum.openzeppelin.com/t/truffle-upgrades-upgrading-to-the-same-implementation-address/29882).

**Comment by DmytroShalaiev** [comment]
Ok, thanks for reply
