### ISSUE TITLE
Updating struct variables

### ISSUE THREAD

**Issue by ItsShadowl** [OpenZeppelin/openzeppelin-upgrades#643]
I have a struct used in the contract storage, which i might want to update its fields later on, currently i try to create a `uint(size) reserved;` every few lines so i can have some reserved storage slot for future fields. Its still untested as the idea just came up yesterday, so i'm not sure if it would work.

Do you think putting a gap in struct will allow for its modification in another upgrade?

```solidity
struct Data {
	uint256 id;
	uint16 dCount; 
	uint16 vCount; 
	uint256[50] __gap; // reserved <<--- Do you think i can reduce the 50 later to allow another type to be created?
	mapping(uint256 => Config) config; //configuration data
}
```
And, another question is if i can change the `uint16 dCount;` to bigger or smaller size later? I know the type saved might be affected the first time, are there any other effects i don't know?

This 👇 seems to help, but not really understandable to me since the OP changed the question before a definitive answer came in
https://forum.openzeppelin.com/t/the-better-way-to-define-the-variable-gap-in-the-proxy-contract/20942/3

**Comment by frangio** [comment]
The answer depends on where you're using the Data struct. If you have a `mapping (uint => Data)` variable, and that's the only place where you use the struct, you don't need to add a __gap varible. You can just append variables when it's in a mapping. Otherwise, yes you could add a gap variable to add variables later.

You can't safely change `uint16 dCount` to a different integer size, unless you run a data migration.

For additional support please ask in the forum!
