### ISSUE TITLE
Upgrading proxy issue with adding a new variable

### ISSUE THREAD

**Issue by itdream-dev** [OpenZeppelin/openzeppelin-upgrades#698]
Hi @frangio, I'm getting the issue when upgrading the proxy by just adding a new state variable and reducing the size of the gap. ( I'm using the truffle upgrade plugin - 1.17.0)

New variables should be placed after all existing inherited variables
Upgraded __gap to an incompatible type

Bad storage gap resize from 46 to 45
Size decrease must match with corresponding variable inserts
Could you please help me with how to solve it?

// Old version
....
uint256[46] private __gap;
// New version
....
address public royaltyRegister;
uint256[45] private __gap;

I couldn't find a mistake based on this link.
[Writing Upgradeable Contracts - OpenZeppelin Docs](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable#storage-gaps)

I uploaded the old file and the new file here.  
[Archive.zip](https://github.com/OpenZeppelin/openzeppelin-upgrades/files/10172404/Archive.zip)

**Comment by skyclean906** [comment]
Hi @frangio,    Could you check the above issue and update me?

**Comment by frangio** [comment]
Resolved [in the forum](https://forum.openzeppelin.com/t/bad-storage-gap-resize-with-truffle/33668/9). The problem was that gap resizing is not available in the Truffle plugin, only in the Hardhat plugin. I've opened issue https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/709 to keep track of that.
