### ISSUE TITLE
Deployed contract address is overriden

### ISSUE THREAD

**Issue by andreas-papageorgiou** [OpenZeppelin/openzeppelin-upgrades#767]
It is unclear why the `deploy` function overrides the deployed contract address.

This prevents the usage of `hardhat-upgrades` with other frameworks/chains where contract addresses are predicted differently.

**Relevant code:**
https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/0ef9efb7447f29a46dc26ffe04a852ba2775d30e/packages/plugin-hardhat/src/utils/deploy.ts#L14-L25

**Comment by ericglau** [comment]
This was done in https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/487 to handle incorrect addresses returned from certain RPC endpoints on chains such as Polygon Mumbai.

Can you provide examples of frameworks/chains that you are using where this should be different?

**Comment by andreas-papageorgiou** [comment]
We are working on integrating with VeChain

**Comment by ericglau** [comment]
This override has been removed in [@openzeppelin/hardhat-upgrades@2.0.0](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%402.0.0) since it no longer seems necessary. 
 Note however that the plugin uses ethers.js for deployments, and ethers.js does [its own calculation of the contract deployment address](https://github.com/ethers-io/ethers.js/blob/3c17cf56b5164236108269ac1e36d66e2843cd1e/src.ts/contract/factory.ts#L112).
