### ISSUE TITLE
Axios Typescript incompabilities

### ISSUE THREAD

**Issue by yangricardo** [OpenZeppelin/openzeppelin-upgrades#801]
Hi
After attempting to update this package, it encountered conflicts with the latest releases of Axios i use in my monorepo packages, which necessitated a difficult downgrade.

![image](https://github.com/OpenZeppelin/openzeppelin-upgrades/assets/5523565/0d048d67-ac72-4451-97bf-ad9e793ad569)

The latest version i can install without global monorepo issues is 1.23.1, the did not require the axios version you use. 
Could you update at least to Axios@1.36.0??

I use some axios typing definitions, like AxiosError and AxiosInstance on my implementation, and it's causing build step errors...

**Comment by ericglau** [comment]
Hi, thanks for reporting this. We plan to upgrade this dependency and will post here when we have an update.

**Comment by frangio** [comment]
How did this cause an error for you? Axios is used internally in one of our dependencies. This shouldn't cause any issues if you declare axios as a dependency in your project.

In your screenshot it doesn't seem like it is declared as a dependency for esg-contracts, so maybe you need to add it there.

**Comment by yangricardo** [comment]
@frangio This is a monorepo project based on Turborepo and NextJS where i have this internal package called esg-contracts. In the main app package i use a more recent version of Axios with more support to Typescripts, to be more precise, currently  i use `axios@1.4.0`. Maybe some peer dependency version of Axios you use directly on indirectly is causing this issue for me... But when i run in that day the command `npm ls axios` i identified some dependency using this `axios@0.21.4`, and its causing type incompabillites or build errors in my environment...

**Comment by ericglau** [comment]
@yangricardo This should be fixed in [@openzeppelin/hardhat-upgrades@2.0.1](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%402.0.1) which has a transitive dependency on `axios@1.4.0`.

Note that v2 of the plugin requires Ethers v6.  If you are on Ethers v5, you would need to update your project -- see [release notes](https://github.com/OpenZeppelin/openzeppelin-upgrades/releases/tag/%40openzeppelin%2Fhardhat-upgrades%402.0.0).
