### ISSUE TITLE
When verifying upgradeable contract: "Bytecode does not match with the current version of ERC1967Proxy in the Hardhat Upgrades plugin"

### ISSUE THREAD

**Issue by SKYBITDev3** [OpenZeppelin/openzeppelin-upgrades#870]
I deployed an `ERC1967Proxy` proxy contract and implementation without using hardhat-upgrades.
Then I tried to verify the contracts using `await run("verify:verify", { address, constructorArguments })`, but got the above error.

I noticed that the artifact `ERC1967Proxy` is obtained from @openzeppelin/upgrades-core:
https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/a41b4317c0ca368cfc6b98b8fe6c33f480bbb766/packages/plugin-hardhat/src/verify-proxy.ts#L17

If I use that version then Etherscan shows a warning when viewing `ERC1967Proxy`s source code:

> The compiled contract might be susceptible to [FullInlinerNonExpressionSplitArgumentEvaluationOrder (low-severity)](https://testnet.bscscan.com/solcbuginfo?a=FullInlinerNonExpressionSplitArgumentEvaluationOrder), [MissingSideEffectsOnSelectorAccess (low-severity)](https://testnet.bscscan.com/solcbuginfo?a=MissingSideEffectsOnSelectorAccess), [AbiReencodingHeadOverflowWithStaticArrayCleanup (medium-severity)](https://testnet.bscscan.com/solcbuginfo?a=AbiReencodingHeadOverflowWithStaticArrayCleanup), [DirtyBytesArrayToStorage (low-severity)](https://testnet.bscscan.com/solcbuginfo?a=DirtyBytesArrayToStorage), [DataLocationChangeInInternalOverride (very low-severity)](https://testnet.bscscan.com/solcbuginfo?a=DataLocationChangeInInternalOverride), [NestedCalldataArrayAbiReencodingSizeValidation (very low-severity)](https://testnet.bscscan.com/solcbuginfo?a=NestedCalldataArrayAbiReencodingSizeValidation) Solidity Compiler Bugs.

The contract was compiled with solidity v0.8.9+commit.e5eed63a, which would be the reason for the warnings and bytcode mismatch. I use the latest version of solidity (0.8.21).

Please fix this issue. Thank you.

**Comment by ericglau** [comment]
The Hardhat Upgrades plugin can only verify proxy source code for proxies that were deployed by the plugin.  This is because verification requires the exact compiler settings which were used to compile the proxy, and those compiler settings (along with the source code) are provided by the plugin during Etherscan verification to match the proxy bytecode that it deployed.

If you deploy proxy contracts without using the plugin, you would need to verify them manually.

However, generally there is no need to deploy newer versions of the proxy contracts than the ones provided by the plugin.  If compiler bugs or other vulnerabilities affect the proxy contracts, we would publish a security advisory for OpenZeppelin Contracts https://github.com/OpenZeppelin/openzeppelin-contracts/security/advisories and would update the plugin to use the newer proxies as needed.

**Comment by SKYBITDev3** [comment]
The latest version of @openzeppelin/contracts is v4.9.3 but openzeppelin-upgrades is still using v4.8.3:

https://github.com/OpenZeppelin/openzeppelin-upgrades/blob/483a43f4856d607dd3b38ab81931e0e777ccb82e/packages/core/package.json#L41C6-L41C29

You should keep it up-to-date.

**Comment by ericglau** [comment]
While some source files have been modified (including for contracts that the proxies depend on) between OpenZeppelin Contracts v4.8.3 and v4.9.3, those specific changes were not deemed to affect proxy functionality.

We generally do not update the version of the proxies used in the Hardhat plugin unless there are changes that affect the proxies.  Updating the versions unnecessarily (if functionality does not change) would cause more difficulties for users.

For example, a benefit of keeping proxy bytecode the same is that many proxy deployments would automatically have "Similar Match Source Code" verified on Etherscan and related block explorers if they were verified by other users before. 

As another example, the Hardhat plugin (as mentioned above) verifies proxy source code with the same bytecode that it deploys.  If a user deploys a proxy but did not verify it, then updates the plugin with an updated proxy, the `verify` task would not work because the plugin's updated proxy source code does not match with what was previous deployed.  There is an issue https://github.com/OpenZeppelin/openzeppelin-upgrades/issues/674 to improve this.
