### ISSUE TITLE
Question/request feature: retrieve the storage slot layout of a contract

### ISSUE THREAD

**Issue by invocamanman** [OpenZeppelin/openzeppelin-upgrades#893]
I know that OZ computes and uses the storage layout of a contract for checking compatibility between upgrades
 Is it possible to access this layout inside a script? ( other than deploy an actual proxy and check the .openzeppelin folder)?

**Comment by ericglau** [comment]
Can you describe your use case?

Typically the storage layout is available from the solc output (if requested from the input settings), although we do additional processing to extract layout when it isn't available, such as for namespaced storage when using ERC-7201.

In Hardhat, after you compile, you can find a `cache` folder with a `validations.json` which includes the complete storage layouts that were computed for each contract.  Is that data format suitable for you, if we make that available from a script?

**Comment by invocamanman** [comment]
Hey! thank you so much.
Actually that `validations.json` is what is was searching for hehe ^^
Actually if that would be available it would help a little, but having it there for me it's ok ^^

I will report what i think it's an small issue:
I think the errors shown when ` unsafeAllowRenames: false,` are not correct.
I think i verify it manually, checking the `validations.json` and also testing in solidity (checking in assembly the storage slots), and everything seems coherent but the errors shown.

In the following repo and branch: https://github.com/0xPolygonHermez/zkevm-contracts/tree/6048728b72b9d3425157b22bce26c5ed8ac49c5e

Currently i'm doing an Upgrade test from a previous to a new system, and i use the `upgradeProxy` function.
Since the contract it's pretty different i want to rename some variables as `_legacy${nameOfVariable}` but as a double check i test the `  unsafeAllowRenames: false,` just to see what errors pop up ( because what should not happen is that i mess up the storage layout for sure):
https://github.com/0xPolygonHermez/zkevm-contracts/blob/6048728b72b9d3425157b22bce26c5ed8ac49c5e/test/contractsv2/PolygonRollupManagerUpgrade.ts#L222

If the flag  ` unsafeAllowRenames: true,`, the test goes though and everything looks fine
If the flag  ` unsafeAllowRenames: false,` there are expected `Replaced` errors, but also seems that somehow it calculates something wrong. For instance: `Inserted _legacyOwner`, (which should be only renames), and some `replaced` variables seems to have an "incorrect" offset, for example `multiplierBatchFee` it's replaced by `_legacyMultiplierBatchFee`, but in the error shows: 
```
contracts/v2/lib/LegacyZKEVMStateVariables.sol:43: Replaced `multiplierBatchFee` with `_legacyVerifyBatchTimeTarget` of incompatible type
```

Finally i try to actually add variables with the ` unsafeAllowRenames: true,` and it does show a correct error. So my guess is that, everything it's fine except the error displayed when `unsafeAllowRenames : false` 

Hope it helps:

To reproduce the error:
Go this repo in this branch:
https://github.com/0xPolygonHermez/zkevm-contracts/blob/6048728b72b9d3425157b22bce26c5ed8ac49c5e/test/contractsv2/PolygonRollupManagerUpgrade.ts#L222

`npm i`
`npx hardhat test/contractsv2/PolygonRollupManagerUpgrade.ts`

You can edit the flag here: https://github.com/0xPolygonHermez/zkevm-contracts/blob/6048728b72b9d3425157b22bce26c5ed8ac49c5e/test/contractsv2/PolygonRollupManagerUpgrade.ts#L222

Node version: v18.16.1
Npm version: 9.5.1

**Comment by ericglau** [comment]
About `validations.json`, that file isn't exposed as part of our public API though, and it's possible that the format can change in the future.  It gets regenerated when you recompile contracts in Hardhat and gets deleted if you run `npx hardhat clean`.  Is that ok for your use case?

In your test, it looks like you are upgrading from `PolygonZkEVMV2Existent` to `PolygonRollupManagerMock`.  Those storage layouts are definitely NOT compatible!  

Your usage of `unsafeAllowRenames: true` does not look safe.  That flag should only be used as a last resort.  If you have specific variables that you want to rename, you should annotate them in the new implementation using `/// @custom:oz-renamed-from x`.  See https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#how-to-rename

**Comment by invocamanman** [comment]
Hey! actually in the mail i can see the historic ^^ And  https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#how-to-rename this was super helpful!!! didn't know about it :D Now i feel it safer,  i wanted to make sure that i count everything right ^^

https://github.com/0xPolygonHermez/zkevm-contracts/tree/162394ddc6d75eb31496823a49b259a0ed61a908 
In this commit it works with `unsafeAllowRenames: false,` ^^

Still think that there are some bug when displaying the errors in `unsafeAllowRenames`, it seems that it detects everything right but somehow displays something wrong if it finds errors

Anyway this was actually super helpfull, thank you so much ^^

**Comment by ericglau** [comment]
Hi, I wanted to clarify my comment.

About `validations.json`, that file isn't exposed as part of our public API though, and it's possible that the format can change in the future.  It gets regenerated when you recompile contracts in Hardhat and gets deleted if you run `npx hardhat clean`.  Is that ok for your use case?

I would suggest not using `unsafeAllowRenames: true` except as a last resort, since it does not let you granularly specify what are the renamed variables (it can be used, but would not allow you to specify a 1-to-1 rename of each variable).  If you have specific variables that you want to rename, you can annotate them in the new implementation using `/// @custom:oz-renamed-from x` instead.  See https://docs.openzeppelin.com/upgrades-plugins/1.x/faq#how-to-rename

I don't see any issues with the storage layouts between your contracts.  For storage layout validations, the comparison is using [levenshtein distances](https://en.wikipedia.org/wiki/Levenshtein_distance) to find the closest matches.  Since you are doing some inserts (shrinking gaps) and renaming a bunch of variables, the errors that you see are what the algorithm determined to be the simplest set of changes.  Allowing variable renames would avoid this.

**Comment by invocamanman** [comment]
About the file, yes! it is ok! :D

About  `unsafeAllowRenames` totally! ^^  didn't know about the annotation thing hehe ^^

About the storage layout errors, i guess it makes sense, its surprising some results of it. Since the storage slot and offset are deterministic, the algorithm could know if a variable was either inserted, or replaced by one or more variables. Also true that might not be worth to edit this if it's over complicated since it accomplish the goal which is telling the user that something it's wrong and where ^^

**Comment by ericglau** [comment]
One counter-example is if a variable is inserted at the beginning of storage layout, then the other variables are shifted and in different slots.  If we assume the slots and offsets to be the same, then the approach that you suggested might say that all variables were renamed, when ideally it should say a variable was inserted.  Neither of these is incorrect though.

> might not be worth to edit this if it's over complicated since it accomplish the goal which is telling the user that something it's wrong and where

Yes, I agree. I don't think that this can be improved much without affecting the error message for other scenarios.

Closing this since there is a way to achieve what you originally asked, but feel free to continue the discussion if needed.

**Comment by invocamanman** [comment]
> One counter-example is if a variable is inserted at the beginning of storage layout, then the other variables are shifted and in different slots. If we assume the slots and offsets to be the same, then the approach that you suggested might say that all variables were renamed, when ideally it should say a variable was inserted. Neither of these is incorrect though.

From my point of view, it actually would mean that you change all the variables, because practically, all variables will change his values. I understand that's opinionated tho.

Thank you so much for your responses ^^
